export interface Product {
  id: string
  name: string
  description: string
  price: number
  category: string
  image: string
  sizes: string[]
  colors: string[]
  inStock: boolean
}

export const products: Product[] = [
  {
    id: "1",
    name: "Vestido Floral Primavera",
    description: "Vestido midi com estampa floral delicada, perfeito para ocasiões especiais",
    price: 189.9,
    category: "Vestidos",
    image: "/elegant-floral-midi-dress-woman.jpg",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Rosa", "Azul", "Verde"],
    inStock: true,
  },
  {
    id: "2",
    name: "Blazer Alfaiataria Premium",
    description: "Blazer estruturado em alfaiataria clássica, ideal para o ambiente corporativo",
    price: 299.9,
    category: "Blazers",
    image: "/elegant-tailored-blazer-woman-professional.jpg",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Bege", "Cinza"],
    inStock: true,
  },
  {
    id: "3",
    name: "Calça Wide Leg Linho",
    description: "Calça pantalona em linho natural, conforto e elegância para o dia a dia",
    price: 159.9,
    category: "Calças",
    image: "/wide-leg-linen-pants-woman-elegant.jpg",
    sizes: ["36", "38", "40", "42", "44"],
    colors: ["Branco", "Bege", "Terracota"],
    inStock: true,
  },
  {
    id: "4",
    name: "Blusa Seda Gola Laço",
    description: "Blusa em seda pura com detalhe de laço no decote, sofisticação garantida",
    price: 219.9,
    category: "Blusas",
    image: "/silk-blouse-bow-neck-woman-elegant.jpg",
    sizes: ["P", "M", "G"],
    colors: ["Branco", "Nude", "Preto"],
    inStock: true,
  },
  {
    id: "5",
    name: "Saia Midi Plissada",
    description: "Saia midi com pregas delicadas, movimento e elegância em uma peça",
    price: 169.9,
    category: "Saias",
    image: "/pleated-midi-skirt-woman-elegant.jpg",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Vinho", "Azul Marinho"],
    inStock: true,
  },
  {
    id: "6",
    name: "Conjunto Tricot Inverno",
    description: "Conjunto de tricot macio: cardigan + top, perfeito para dias frios",
    price: 249.9,
    category: "Conjuntos",
    image: "/knit-cardigan-set-woman-cozy-elegant.jpg",
    sizes: ["P", "M", "G"],
    colors: ["Caramelo", "Off White", "Cinza"],
    inStock: true,
  },
  {
    id: "7",
    name: "Vestido Longo Festa",
    description: "Vestido longo com caimento fluido, ideal para eventos noturnos",
    price: 389.9,
    category: "Vestidos",
    image: "/long-evening-dress-woman-elegant-party.jpg",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Vinho", "Verde Esmeralda"],
    inStock: true,
  },
  {
    id: "8",
    name: "Camisa Oversized Linho",
    description: "Camisa ampla em linho, estilo despojado e confortável",
    price: 139.9,
    category: "Camisas",
    image: "/oversized-linen-shirt-woman-casual-chic.jpg",
    sizes: ["P", "M", "G"],
    colors: ["Branco", "Azul Claro", "Bege"],
    inStock: true,
  },
  {
    id: "9",
    name: "Calça Alfaiataria Reta",
    description: "Calça de alfaiataria com corte reto, elegância atemporal",
    price: 199.9,
    category: "Calças",
    image: "/straight-tailored-pants-woman-professional.jpg",
    sizes: ["36", "38", "40", "42", "44"],
    colors: ["Preto", "Cinza", "Azul Marinho"],
    inStock: true,
  },
  {
    id: "10",
    name: "Top Cropped Tricot",
    description: "Top cropped em tricot canelado, versátil e moderno",
    price: 89.9,
    category: "Tops",
    image: "/cropped-knit-top-woman-modern-casual.jpg",
    sizes: ["P", "M", "G"],
    colors: ["Preto", "Branco", "Caramelo"],
    inStock: true,
  },
  {
    id: "11",
    name: "Jaqueta Jeans Premium",
    description: "Jaqueta jeans com lavagem especial e corte moderno",
    price: 229.9,
    category: "Jaquetas",
    image: "/premium-denim-jacket-woman-stylish.jpg",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Azul Claro", "Azul Escuro", "Preto"],
    inStock: true,
  },
  {
    id: "12",
    name: "Vestido Tubinho Executivo",
    description: "Vestido tubinho clássico, perfeito para o ambiente corporativo",
    price: 179.9,
    category: "Vestidos",
    image: "/sheath-dress-woman-professional-elegant.jpg",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Azul Marinho", "Vinho"],
    inStock: true,
  },
  {
    id: "13",
    name: "Shorts Alfaiataria Alto",
    description: "Shorts de cintura alta em alfaiataria, elegante e confortável",
    price: 129.9,
    category: "Shorts",
    image: "/high-waist-tailored-shorts-woman-elegant.jpg",
    sizes: ["36", "38", "40", "42"],
    colors: ["Preto", "Bege", "Branco"],
    inStock: true,
  },
  {
    id: "14",
    name: "Blusa Babados Romântica",
    description: "Blusa com babados delicados, feminilidade e charme",
    price: 149.9,
    category: "Blusas",
    image: "/ruffle-blouse-woman-romantic-feminine.jpg",
    sizes: ["P", "M", "G"],
    colors: ["Branco", "Rosa Claro", "Lavanda"],
    inStock: true,
  },
  {
    id: "15",
    name: "Macacão Longo Elegante",
    description: "Macacão longo com amarração na cintura, sofisticação em uma peça",
    price: 269.9,
    category: "Macacões",
    image: "/elegant-long-jumpsuit-woman-sophisticated.jpg",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Verde Militar", "Terracota"],
    inStock: true,
  },
  {
    id: "16",
    name: "Cardigan Longo Tricot",
    description: "Cardigan longo em tricot macio, aconchego e estilo",
    price: 189.9,
    category: "Cardigans",
    image: "/placeholder.svg?height=400&width=300",
    sizes: ["P", "M", "G"],
    colors: ["Caramelo", "Cinza", "Off White"],
    inStock: true,
  },
  {
    id: "17",
    name: "Saia Lápis Couro Eco",
    description: "Saia lápis em couro ecológico, atitude e elegância",
    price: 159.9,
    category: "Saias",
    image: "/placeholder.svg?height=400&width=300",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Vinho", "Caramelo"],
    inStock: true,
  },
  {
    id: "18",
    name: "Vestido Chemise Listrado",
    description: "Vestido chemise com listras clássicas, estilo atemporal",
    price: 169.9,
    category: "Vestidos",
    image: "/placeholder.svg?height=400&width=300",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Azul/Branco", "Preto/Branco"],
    inStock: true,
  },
  {
    id: "19",
    name: "Calça Jogger Premium",
    description: "Calça jogger em tecido nobre, conforto sem abrir mão do estilo",
    price: 179.9,
    category: "Calças",
    image: "/placeholder.svg?height=400&width=300",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Cinza", "Verde Militar"],
    inStock: true,
  },
  {
    id: "20",
    name: "Blusa Ombro a Ombro",
    description: "Blusa ciganinha com elástico, feminilidade e frescor",
    price: 119.9,
    category: "Blusas",
    image: "/placeholder.svg?height=400&width=300",
    sizes: ["P", "M", "G"],
    colors: ["Branco", "Coral", "Azul Claro"],
    inStock: true,
  },
  {
    id: "21",
    name: "Conjunto Social Feminino",
    description: "Conjunto blazer + calça em alfaiataria premium, poder e elegância",
    price: 449.9,
    category: "Conjuntos",
    image: "/placeholder.svg?height=400&width=300",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Preto", "Cinza", "Azul Marinho"],
    inStock: true,
  },
  {
    id: "22",
    name: "Vestido Wrap Estampado",
    description: "Vestido transpassado com estampa exclusiva, valoriza todas as silhuetas",
    price: 209.9,
    category: "Vestidos",
    image: "/placeholder.svg?height=400&width=300",
    sizes: ["P", "M", "G", "GG"],
    colors: ["Floral Azul", "Floral Rosa", "Animal Print"],
    inStock: true,
  },
]

export const categories = [
  "Todos",
  "Vestidos",
  "Blusas",
  "Calças",
  "Saias",
  "Blazers",
  "Conjuntos",
  "Jaquetas",
  "Tops",
  "Shorts",
  "Macacões",
  "Cardigans",
  "Camisas",
]
